apiVersion: v1
kind: Service
metadata:
  name: todo-extra-front
spec:
  selector:
    app: todo-extra-front
  ports:
    - protocol: TCP
      port: 4200           # Service port
      targetPort: 4200   # Port your app listens on within the pod
  type: NodePort
