apiVersion: v1
kind: Pod
metadata:
  name: yamlmongodb
  labels:
    app: yamlmongodb
    role: master
    tier: todo-app
spec:
  containers:
    - name: yamlmongodb
      image: mongo:latest
      ports:
        - containerPort: 27017
