apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: mongodb
    role: master
    tier: todo-app
spec:
  containers:
    - name: mongodb
      image: mongo:latest
      ports:
        - containerPort: 27017
