apiVersion: v1
kind: Service
metadata:
  name: todo-front
spec:
  selector:
    app: todo-front
  ports:
    - protocol: TCP
      port: 3000           # Service port
      targetPort: 3000   # Port your app listens on within the pod
  type: NodePort
